pipeline:
  identifier: Build_goHelloWorldServer_1688131784033
  name: Build goHelloWorldServer
  orgIdentifier: default
  projectIdentifier: Partner_Bootcamp_Yan_Luanan
  stages:
    - stage:
        name: "Build test and Push "
        identifier: Build_test_and_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Unit Test
                  identifier: Run_Unit_Test
                  spec:
                    connectorRef: Harness_bootcamp
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      go get gotest.tools/gotestsum
                      gotestsum --format=standard-verbose --junitfile unit-tests.xml || true
                      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push image to Docker Registry
                  identifier: Build_and_push_image_to_Docker_Registry
                  spec:
                    connectorRef: Harness_bootcamp
                    repo: "[yljj]/[minikube]mydockerhub/ci_tutorial_repo"
                    tags:
                      - <+pipeline.sequenceId>
    - stage:
        name: Run integration test
        identifier: Run_integration_test
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Windows
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - stepGroup:
                  name: Untitled
                  identifier: 7e33bd7f-c645-57a7-95da-ede6a3330aae
                  steps:
                    - step:
                        type: Background
                        name: Background_1
                        identifier: Background_1
                        spec:
                          shell: Powershell
              - step:
                  type: Run
                  name: Test server connection
                  identifier: Test_server_connection
                  spec:
                    shell: Powershell
                    command: |-
                      sleep 10
                      curl localhost:8080
                      curl localhost:8080?Hello!_I_am_a_nice_demo!
                  description: curlimages/curl:7.73.0
  properties:
    ci:
      codebase:
        connectorRef: Bootcamp_Harness
        build: <+input>
